### ISSUE TITLE
Robot falling when starting roscontrol in effort mode

### ISSUE THREAD

**Issue by NoelieRamuzat** [stack-of-tasks/roscontrol_sot#20]
Hi, 
When I start the controller in effort mode on gazebo using:
`roslaunch roscontrol_sot_talos sot_talos_controller_gazebo_effort.launch`
the robot is falling. 

I already had this problem before and @olivier-stasse fixed it but I cannot find the commit which did it. If I remember well the problem came from these two commits:
https://github.com/stack-of-tasks/roscontrol_sot/commit/f210e5f7a6c45fd6ae4e6af1ec301605076be983#diff-1ff5930c886e42394b88b0f8a8c66481

https://github.com/stack-of-tasks/roscontrol_sot/commit/9dd2e8a21222ec238b7beec612aba3cf0455421a#diff-1ff5930c886e42394b88b0f8a8c66481

The second commit fixes the first one but removes too much lines.
The lines: 
```
    // But in effort mode it means that we are sending 0
    // Therefore implements a default PD controller on the system.
    // Applying both to handle mixed system.
    localStandbyEffortControlMode(period);
    localStandbyVelocityControlMode(period);
    localStandbyPositionControlMode();
```

Should not have been removed from the `update` method and should be added at the end of the method, in the final `else` after the `try - catch`:

```
else {
    /// Update the sensors.
    fillSensors();
    try {
      sotController_->setupSetSensors(sensorsIn_);
    } catch (std::exception &e) {
      ROS_ERROR_STREAM("RCSotController::update: " << e.what());
      throw;
    }
    // But in effort mode it means that we are sending 0
    // Therefore implements a default PD controller on the system.
    // Applying both to handle mixed system.
    localStandbyEffortControlMode(period);
    localStandbyVelocityControlMode(period);
    localStandbyPositionControlMode();
  }
}
```

Thank you for your help.

**Comment by olivier-stasse** [comment]
Just adding the last block you wrote should do it.
