### ISSUE TITLE
Error message when SoT exceeds the period

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/roscontrol_sot#3]
It would be nice to get a ROS error message when one iteration of SoT exceeds the period. This does not have to be during execution. It could also be when writing the logs to the hard disk.

**Comment by jmirabel** [comment]
I am working on it.

**Comment by olivier-stasse** [comment]
Normally you can see that in the log files.
If it is sporading and short (2xtimes the period) this is not really a problem for RT_PREEMPT_PATCH.
When this is systematic then it is not blocking the OS, but this is bad for the robot.
For debugging issue looking at the log files has been good enough.

But anyway as long it is not introducing lag in the system this is fine with me.

**Comment by olivier-stasse** [comment]
Analysis of duration is allowing to check when the computation time is taking too much time.
I am closing the comment.
Please feel free to reopen it if needed.
