### ISSUE TITLE
Initializing sot_controller failed

### ISSUE THREAD

**Issue by ozgurgulsuna** [stack-of-tasks/roscontrol_sot#33]
I can launch talos succesfully with;

`roslaunch talos_gazebo talos_gazebo.launch`

When I launch;

`roslaunch roscontrol_sot_talos sot_talos_controller.launch`

I got the error;
```
 Read Sot Vector State Param 
[ERROR] [1659453749.384319922, 3.064000000]: Initializing controller 'sot_controller' failed
```

**Comment by olivier-stasse** [comment]
Dear @ozgurgulsuna thanks for your interest in our work.
It looks like you are not able to load the plugin corresponding to `sot_controller`.
Could you display the output of `dpkg -l | grep robotpkg` ?

**Comment by ozgurgulsuna** [comment]
@olivier-stasse 
```
ii  robotpkg-dynamic-graph-v3                          4.4.0r1                                         amd64        Efficient data-flow C++ library for robotics
ii  robotpkg-example-robot-data                        4.0.1                                           amd64        Robot URDFs for benchmarking and developed examples
ii  robotpkg-hpp-fcl+doc                               1.7.8                                           amd64        Humanoid Path Planner (collision detection and distance computations)
ii  robotpkg-pinocchio                                 2.6.8                                           amd64        Efficient rigid body dynamics
ii  robotpkg-py27-eigenpy                              2.7.6                                           amd64        Eigen bindings to python
ii  robotpkg-py27-hpp-fcl                              1.8.1                                           amd64        Humanoid Path Planner (collision detection and distance computations (python bindingss))
ii  robotpkg-py27-pinocchio                            2.6.8                                           amd64        Efficient rigid body dynamics (python bindings)
ii  robotpkg-sot-core-v3                               4.11.6r1                                        amd64        Hierarchical task based control of humanoid robots

```

**Comment by olivier-stasse** [comment]
Thanks, could you confirm that you followed:
https://stack-of-tasks.github.io/sot-doc/doxygen/HEAD/tutorial_whole_body_motion.html
?

**Comment by olivier-stasse** [comment]
The tutorial is misleading. Indeed the line 
```sudo apt-get install robotpkg-talos-dev```
should be done for both version.
(@nim65s could you confirm that it is also working on noetic ?)

**Comment by ozgurgulsuna** [comment]
I am working on ros melodic and cannot install robotpkg-talos-dev , it gives the following error,
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package robotpkg-talos-dev
```

**Comment by ozgurgulsuna** [comment]
Also I get the following error,
`sudo apt install robotpkg-py27-talos-dev`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package robotpkg-py27-talos-dev
```

**Comment by olivier-stasse** [comment]
Indeed according to http://robotpkg.openrobots.org/rbulk/robotpkg-wip/wip/py-talos-dev/index.html#py27-talos-dev-20201126 this should be working.
Let me check but I need a bit of time for that.

**Comment by olivier-stasse** [comment]
Dear @ozgurgulsuna ,
Building a fresh melodic install from the Dockerfile located here:
https://github.com/stack-of-tasks/sot-doc/blob/master/Dockerfile/Dockerfile.melodic
I was able to see the package `robotpkg-py27-talos-dev` but I cannot install it due to unavailable binaries.

It is probably an update of some submodules which has not been pushed and led to an incorrect situation in our build farm: 
http://robotpkg.openrobots.org/rbulk/robotpkg-wip/wip/py-sot-core-v3/py27-sot-core-v3-4.11.7/Ubuntu-18.04-x86_64/bulk.html

@nim65s could you confirm ? If possible provide an update ? I do not understand why the documentation wants to be installed at the root level. 

Unfortunately as many people are in summer break, fixing the issue make takes some time.

**Comment by nim65s** [comment]
`sudo apt update && sudo apt install robotpkg-py27-talos-dev` should be fine now. Sorry for the delay. Please reopen if you get other errors.
