### ISSUE TITLE
ptorque and joint_angles not working

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/roscontrol_sot#5]
When retrieving information from the device, signals ptorque and joint_angles are constantly zero (even though they are of the correct size and their time stamp gets updated).
I am using the installation via binary packages.
It seems the cause of this behaviour is that the macro TEMPERATURE_SENSOR_CONTROLLER is not defined.

**Comment by olivier-stasse** [comment]
Dear Gabriele,
This was a problem from the settings of robotpkg.
Version 0.07r1 fixes the problem.
It is working on my PC, could you confirm that this is working for you ?
Thanks in advance,
Olivier.

**Comment by gabrielebndn** [comment]
I confirm that the problem is solved
