### ISSUE TITLE
Gains not used

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/roscontrol_sot#7]
Gains are not used in the for loop below. @olivier-stasse is this a programming mistake or are they not necessary ?

https://github.com/stack-of-tasks/roscontrol_sot/blob/0385fe4e4dbc69514e958c23d2928d0f29566f7b/src/roscontrol-sot-controller.cpp#L964

**Comment by olivier-stasse** [comment]
This branch is incomplete. When in torque mode the proper way to control
the joint is given in branch master/devel. Ideally the part inside the loop
should go into a joint class encapsulating the roscontrol one.

Le lun. 3 juin 2019 à 17:55, Joseph Mirabel <notifications@github.com> a
écrit :

**Comment by jmirabel** [comment]
Thank. I solved my issues.
